src/main.js
Refs https://github.com/mapbox/node-pre-gyp/pull/175.
=> Pass --runtime when calling npm

src/cli.js, src/main.js, test/main.js
I've added a flag `-w` to allow this to rebuild a single module, if you so choose. Otherwise, it still just rebuilds everything like before. See #26.
=> Add flag for which node module to build

src/cli.js
=> Resolve relative path from path.txt

README.md
=> Mention require-rebuild

src/cli.js
=> Add dist-url switch to cli

README.md
- Fixes the examples so that the version numbers are no longer prefixed with `v`, which no longer works with Electron 1.3.1 on macOS at least. With `v` you get an error about common.gypi missing.
- Update one of the examples to use async/await and have fewer hardcoded values
- Change io.js references to Node.js
=> Update the README with fixed examples, async/await, mention Node

src/cli.js
Fixed the path resolution and added another check so we get a nicer error message when things fail.
=> Fix CLI path resolution

src/rebuild.js
Holy dam I've had enough of NPM....
=> Locate node-gyp dynamically to avoid hoisting issues

src/rebuild.js
=> Actually use the resolved path

package.json
Because no one checked 😆 
I feel bad 😢
=> Fix entry point

README.md
For some reason I wasn't aware of #148. Here are some updates:
* Added a section for Forge
* general readme cleanups
CC: @MarshallOfSound
=> Readme updates for the packager-example branch

src/rebuild.js, test/rebuild.js
=> Test arch and ABI when checking if we should rebuild

src/rebuild.ts, test/fixture/native-app1/package.json, test/rebuild.ts
=> Don't rebuild modules that have been prebuilt with prebuild

.travis.yml, package.json, src/cli.ts, src/read-package-json.ts, src/rebuild.ts, test/rebuild.ts
fs-promise is deprecated 👍 
>npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
=> Replace fs-promise with fs-extra

src/cli.ts
=> CLI default types should be "prod,optional"

README.md
options object has misnamed property in sample code in README
=> correct buildPath options in comment code sample

README.md, src/cli.ts, src/rebuild.ts, test/rebuild.ts
Solves https://github.com/electron/electron-rebuild/issues/207
Added CLI `-b` and `--debug` argument to rebuild native addons in debug mode.
Additional optional debug argument to rebuild functions.
=> Add debug build option

README.md
specifies that node v6.0.0 or greater is required
=> docs: include Node version requirement

package.json, src/ambient.d.ts, src/cli.ts, src/read-package-json.ts, src/rebuild.ts, test/fixture/native-app1/package.json, test/rebuild.ts
* Modernize `fs-extra` usage
* Upgrade all the things
* `npm test` runs `tslint`
=> chore: upgrade dependencies

src/rebuild.ts
- changing HOME breaks asdf (https://github.com/asdf-vm/asdf) #271 
- Also should fix #117
=> fix: Use npm_config_devdir instead of setting HOME

.travis.yml, package-lock.json, package.json
Closes #326 (actually updates `package-lock.json`)
Fixes #325 
Closes #329
=> chore(deps): upgrade node-gyp to ^6.0.1

package-lock.json, package.json, src/electron-locator.ts, src/rebuild.ts, test/rebuild.ts
* Upgrade a bunch of the dependencies without requiring a major version bump
* Refactor some of the code for clarity (I've been trying to push old PRs over the finish line)
=> Code cleanup & dependency upgrades

test/helpers/rebuild.ts, test/rebuild.ts
=> test: refactor rebuilt expectations to be more readable

package-lock.json, package.json, src/rebuild.ts, test/electron-locator.ts, test/rebuild-yarnworkspace.ts, test/rebuild.ts
=> refactor: replace spawn-rx with @malept/cross-spawn-promise

.circleci/config.yml, package-lock.json, package.json, src/rebuild.ts
=> feat: update node-gyp to support apple silicon

.circleci/config.yml, .gitignore, README.md, package-lock.json, package.json
=> build: add support for code coverage & uploading to codecov

package-lock.json, package.json
This is mostly to trigger a release for #400.
=> build(deps): upgrade ora to ^5.1.0

src/module-rebuilder.ts, src/module-type/prebuildify.ts, src/node-api.ts, src/rebuild.ts, test/module-type-prebuildify.ts
It seems that `prebuildify` is now the recommended way to use `prebuild` (over `prebuild-install`). Detect native modules using `prebuildify` and don't try to rebuild the native module if an existing bundled, compatible native module for the given platform, arch, and ABI exists.
=> feat: detect modules using prebuildify

package.json, src/cli.ts, yarn.lock
=> fix: replace colors with chalk

.circleci/config.yml, package.json, test/fixture/native-app1/package.json, yarn.lock
=> build: fix CI

.circleci/config.yml, package.json, src/clang-fetcher.ts, src/sysroot-fetcher.ts, test/arch.ts, test/fixture/native-app1/package.json, test/helpers/module-setup.ts, test/rebuild.ts, yarn.lock
As in title, no user facing changes
=> build: update dependencies to clean up yarn audit

.github/semantic.yml
=> chore: use action-semantic-pull-request

README.md
The package and repo have been renamed.
=> docs: update Electron Packager references

.circleci/config.yml, package.json, yarn.lock
=> ci: bump continuousauth/npm orb to 2.1.0

src/module-walker.ts
When removing a pnpm module, pnpm might leave a dangling symbolic link to the folder that no longer exists. In this case `realpath` call will fail with ENOENT and fail the build that could otherwise continue without issues.
=> fix: runtime error after removing pnpm module
