src/main.js, test/main.js
Fix checking for installed headers to actually pass in nodeVersion as the first param. This also includes a test.
=> Fix checking for installed headers

src/cli.js
This will allow an electron-cli module to use the electron that is specified by the app.
=> Add option for specifying electron-prebuilt path

src/main.js
Before, on windows the electron console output may not lead to stdout so electron-rebuilt failed to detect version.
setting the ELECTRON_NO_ATTACH_CONSOLE env variable fix this
Fixes #37
=> On Windows, don't attach to current console session

package.json, src/cli.js, src/main.js, src/node-pre-gyp-fix.js
[node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp) is used by some popular projects (like [serialport](https://www.npmjs.com/package/serialport)) to provide precompiled binaries to most users. In electron's case it falls back to compilation and does so successfully.
Unfortunately, node-pre-gyp doesn't detect electron during runtime and tries to load native addons through the "normal" node path (...../node-v1234-os-arch.... instead of electron-v1234-os-arch).
Some pull requests have been submitted that fix the issue: mapbox/node-pre-gyp#177 and mapbox/node-pre-gyp#187 but they have been open for some months without any activity.
So I created a command-line switch (-p or --pre-gyp-fix) that copies the bindings' folder to the path current node-pre-gyp versions expect it to be in, …
=> Workaround for node-pre-gyp's lack of electron runtime detection (and a little bugfixing)

src/cli.js, src/main.js
Added a flag for -c to allow you to pass different commands (i.e. install) to npm via the module. Still defaults to `rebuild`
=> Allow different npm commands via -c flag

README.md, src/cli.js, src/main.js
Re-export the `preGypFixRun` function from `main.js` so it's easier to import from the outside.
=> Document the node-pre-gyp workaround and make it easier to invoke

src/main.js
This PR fixes #66 
Basically `node-gyp` treats versions `1.x.y` to `3.x.y` as `iojs` so the major bump to `1.x.y` on electron caused node-gyp to download to a `iojs-{version}` folder instead of `{version}` folder.
This PR simply checks if either exists
/cc @parro-it @jostrander
=> Check for canary file in the `iojs` header folder aswell.

src/main.js
`ATOM_SHELL_INTERNAL_RUN_AS_NODE` was not part of the `1.0` and removed in `1.2`.
Refs electron/electron#5682
Closes https://github.com/electron/electron-rebuild/issues/70
=> Use ELECTRON_RUN_AS_NODE env var

README.md
I've spent a long time figuring out why i couldn't rebuild my modules. On windows, even if your configuration is correct , there is environment difficulties and running it throught an npm script do the job. 
I found some informations by reading the issues but maybe it could be nice to have this in the main documentation
=> Added a notice about windows errors

contributing.md
I just copied the doc from `electron/electron`, updated the project name, and took out the electron-specific bits about C++ and Python code style, etc.
cc @jlord @kevinsawicki
=> add contributing doc

.travis.yml, package.json, src/cli.js, src/electron-locater.js, test/electron-locater.js
Fixes #91
This checks the `electron` node_modules directory and attempts to resolve the `electron` and `electron-prebuilt` packages as fallbacks.
=> Add new methods to find the electron-prebuilt directory

package.json
Noticed these were pointing to the old repo location. ✏️ 👍
=> Update package.json's URLs.

package.json
Following up on https://github.com/electron/electron-rebuild/issues/91#issuecomment-241937379
This updates `version` in package.json to match what's on npm.
I guess this was me messing up somehow but it looks like [this has happened before](https://github.com/electron/electron-rebuild/issues/79)?
=> update version in package.json to match npm

src/main.js
This either downloads or rebuilds the binary module during rebuild.
Closes #59
=> Always update the binary on rebuild

src/cli.js, src/main.js, src/spawn.js
Fixes #96 
Fixes #61 
This also sneaks in a `--log` arg which automatically pipes the output of the rebuild to `process.stdout`
=> Add --ignore-optdeps and --ignore-devdeps CLI params

package.json, src/electron-locater.js, src/index.js
This PR exports the `locateElectronPrebuilt` method as well as makes it a bit easier to decide what gets exported and what doesn't -cc @zeke
=> Export more methods and make an index.js file

.travis.yml, package.json, src/rebuild.js
* Replaces the standard node-gyp bindings template strings
Fixes #137
=> Handle the case where the module specifies an output path

src/rebuild.js
Add missing “not” in error message
=> Fix misleading error message

src/rebuild.ts
I see this on Ubuntu 14.04.5 LTS. Turns out there are no `*.node` files for `fsevents`, and `electron-rebuild` breaks with `TypeError: Path must be a string. Received undefined`.
This fix just ensures that if there are no `*.node` files then we bow out gracefully.
```
electron-rebuild rebuilding: fsevents +81ms
electron-rebuild rebuilding fsevents with args [ 'rebuild',
'--target=1.6.11',
'--arch=x64',
'--dist-url=https://atom.io/download/electron',
'--build-from-source',
'--module_name=fse',
'--module_path=/home/rof/src/github.com/user/repo/node_modules/fsevents/lib/binding/Release/electron-v1.6-linux-x64',
'--remote_path=./v1.1.2/',
'--package_name=fse-v1.1.2-electron-v1.6-linux-x64.tar.gz',
'--host=https://fsevents-binaries.s3-us-west-2.amazonaws.com' ] +0ms
electron-rebuild built: …
```
=> fix path must be string when no `*.node` files found

README.md, src/cli.ts, src/main.ts, src/rebuild.ts, test/rebuild.ts, tslint.json
This makes the `rebuild` API accept an options object instead of like 10 consecutive argument.
Gives us more control over the properties / arguments and lets us add things easier in the future in a non-breaking way.
Also note that this is a backwards compatible change (see the test file updates)
=> Switch to passing args in an options object instead of one long chain

README.md, src/cli.ts, src/rebuild.ts, test/read-package-json.ts, test/rebuild.ts
Adapted from changes originally in #178 (can be considered a replacement for that, with the additional benefit of handling nested module names).
Fixes #151
/cc @jkuri
=> Add --only option to build whitelisted modules

package.json, src/ambient.d.ts, src/rebuild.ts
Fixes #217. `node-pre-gyp` added support for a new `{libc}` token which landed here: https://github.com/mapbox/node-pre-gyp/commit/db6ab8019123bdb07cce02bfb4f028dd382b87ff and was released in v0.6.39.
I notice that `electron-rebuild` has no `node-pre-gyp` dependency to update.
=> Add `{libc}` token replacement and libc detection.

README.md
I think some docs is in order. The support for `prebuild-install` is completely hidden in the code.
Closes https://github.com/electron/electron-rebuild/issues/229
cc @juliangruber @vweevers
=> Add docs on how electron-rebuild works with prebuild-install

src/cache.ts, src/rebuild.ts
* Generates a deterministic hash of each directory being rebuilt
* hash is based on options passed to electron-rebuild and contents of
directory
* Checks if a cache entry exists for that hash
* If not, builds like normal
* Then stores the entire state of that module directory as a gzipped
blob in the users cache directory
* If yes, pulls the module directory state and applies it directly to
that module
Please note that this is kinda experimental, I would NOT reccomend using
it on CI, but for local dev where rebuilding modules constantly can get
very annoying I would 100% reccomend using it.
This is delibrately being left undocumented so it can stablize a bit or
potentially be removed at any point.
=> feat: add a caching option

package.json
This should allow installation when installing electron-rebuild from git.
=> chore: use prepare instead of prepublish in package.json scripts

src/cli.ts
👋 I found a tiny bug in the argument parsing. By default, yargs automatically installs its own `--version` command and processes it before electron-rebuild has a chance to process it itself. (It looks like this was introduced in [yargs 9.0.0](https://github.com/yargs/yargs/blob/master/CHANGELOG.md#900-2017-09-03).) By calling [`.version(false)`](http://yargs.js.org/docs/#api-versionversionboolean) explicitly, we can disable this and ensure that it's interpreted properly.
Before:
```
> electron-rebuild --help
Usage: electron-rebuild --version [version] --module-dir [path]
Options:
-h, --help                   Show help                               [boolean]
-v, --version                Show version number                     [boolean]
-f, --force                  Force rebuilding modules, …
```
=> Disable yargs' automatic --version command

package-lock.json, src/rebuild.ts
We should be using the Electron JS redirect rather than the one on the Atom website
=> chore: use the new electronjs.org headers URL

package-lock.json, package.json, src/cache.ts, src/rebuild.ts
The main changes are upgrading TypeScript (which required some source changes) and upgrading node-gyp.
Closes #311.
Closes #315.
=> chore: upgrade dependencies

test/fixture/native-app1/package.json, test/rebuild.ts
`cmark-gfm` [no longer builds](https://app.circleci.com/jobs/github/electron/electron-rebuild/291), I think due to a change in N-API. So, I've replaced it with `leveldown`.
=> test: replace electron-markdown/cmark-gfm with level/leveldown

package-lock.json, package.json, src/cache.ts, src/cli.ts, src/electron-locator.ts, src/main.ts, src/prebuild-shim.ts, src/read-package-json.ts, src/rebuild.ts, test/electron-locator.ts, test/read-package-json.ts, test/rebuild.ts
This lets us use `eslint-plugin-mocha` to avoid `.only` in tests, among other things.
=> refactor: replace tslint with eslint

README.md, src/cli.ts, src/rebuild.ts
* passes through --prebuilt-tag-prefix option to prebuild-install call to get
scoped modules from github
This will help [unblock users of `node-serialport`](https://github.com/node-serialport/node-serialport/issues/1672#issuecomment-448016260) to use the latest prebuilt binaries and any other package that uses custom tag prefixes with electron-rebuild.
=> feat: add --prebuild-tag-prefix option for prebuild-install

README.md
Fix headerURL in README (changed in #299)
cf. https://github.com/electron/electron/blob/master/docs/breaking-changes.md#node-headers-url
=> docs: fix default of headerURL in README

README.md, src/rebuild.ts
When you try to retrieve headers via `https://electronjs.org/headers/v4.0.8/node-v4.0.8-headers.tar.gz`, it will cause the following HTTP response chain:
* `301 ➡️ https://www.electronjs.org/headers/v4.0.8/node-v4.0.8-headers.tar.gz`
* `302 ➡️ [S3 bucket URL]`
* `200`
We should save folks an HTTP request when they rebuild modules.
=> fix: remove one layer of HTTP redirects for Electron headers

src/main.ts, src/rebuild.ts, test/rebuild.ts
Among other things:
* The sequential API for `rebuild()`
* `createOptions`
* `rebuildNativeModules`
BREAKING CHANGE: remove deprecated APIs
=> refactor: remove deprecated APIs

src/module-rebuilder.ts, src/rebuild.ts, typings/ambient.d.ts
Turns out the module uses command line arguments :cry: but it's still better than using `spawn`.
Also extracts the actual module rebuilding to its own class.
=> refactor: use node-gyp as a module instead of shelling out

README.md, src/cli.ts
This change adds clarification to the docs explaining that modules defined with `-w` or `--which-module` must match those defined in types. In the code, this is enforced here
https://github.com/electron/electron-rebuild/blob/fac334634e856d5438fad74d34c91a41e30a43fa/src/rebuild.ts#L154-L165
=> docs: Clarify that -w is only respected when modules are a subset of those matching current types

package-lock.json, package.json, src/rebuild.ts, test/electron-locator.ts, test/rebuild-yarnworkspace.ts, test/rebuild.ts
Effectively required to make it easier to debug issues with running commands (e.g., #382, or the Node 14 errors in CI). This module is also used in other modules across the Electron tool ecosystem.
=> refactor: replace spawn-rx with @malept/cross-spawn-promise

.circleci/config.yml, .github/dependabot.yml, package-lock.json, package.json, src/rebuild.ts, test/electron-locator.ts, test/fixture/native-app1/package.json, test/fixture/workspace-test/child-workspace/package.json, test/helpers/electron-version.ts, test/rebuild-yarnworkspace.ts, test/rebuild.ts
A summary of changes based on the commit history:
* Enable tests against Node 14 - `@nlv8/signun` doesn't work for some reason _(likely to do with enabling warnings-as-errors somewhere in C-land)_, so replace it with `@newrelic/native-metrics`
* Refactor `Object.assign` usage with modern Object spread syntax
* Re-enable workspace tests _(couldn't run `node-gyp-build` during install due to a race condition on Windows?)_ by replacing the native modules used for testing
* Update dependencies via `npm audit fix`
* DRY up the references to the Electron test version/range by only having one place to change the test version (`package.json`)
* Upgrade the Electron devDependency to ^10
* Enable Dependabot
=> build: test/CI enhancements

src/module-rebuilder.ts, src/rebuild.ts, typings/ambient.d.ts
Technically it's a refactor, but it's also a fix/perf improvement. Tests run significantly faster probably because it removes a layer of indirection (i.e., shelling out). I believe we may be able to do something similar with `prebuild-install` and just get rid of `@malept/cross-spawn-promise` as a dependency (still needs to be a devDependency).
This is ported from #363 
> Turns out the module uses command line arguments cry but it's still better than using spawn.
>
> Also extracts the actual module rebuilding to its own class.
Additionally, it refactors `locateBinary` to be a little more efficient in the worst case.
=> fix: use node-gyp as a module instead of shelling out

package.json, tsconfig.json
* only package files from the `lib` folder
* Emit ES2018 (Node 10) JavaScript from `tsc`
=> build: reduce released module size

.circleci/config.yml, src/module-rebuilder.ts, src/rebuild.ts, test/helpers/checksum.ts, test/rebuild-yarnworkspace.ts, test/rebuild.ts
It should have iterated through all of the node-gyp commands since `node-gyp rebuild` pushes `clean`, `configure`, and `build` commands to the `todo` list. Also:
* ensures that the module path is the current working directory when it's running
* adds a regression test
Fixes #404
=> fix: run node-gyp rebuild correctly

README.md, package-lock.json, package.json, src/clang-fetcher.ts, src/constants.ts, src/module-rebuilder.ts, src/rebuild.ts, test/rebuild.ts
As in title, this makes it so that when building native modules for Electron you can optionally use the `clang` binary that Electron used to build.  This guarantees support for the same set of compiler features.
Closes #432
=> feat: use electron clang to build native modules

src/rebuild.ts
Electron Forge runs `electron-rebuild` during packaging regardless of whether the Electron app has any native modules (because currently, it doesn't know if it does at that point). This is problematic because that means that `node-abi` is called every time, and if there's a problem with version bumping `node-abi`, they'll incorrectly get the mismatch error.
This pull request should change the rebuilder to only call `node-abi` when `rebuildModuleAt(modulePath)` is called, and cache the result.
=> fix: only call node-abi when there's a module to rebuild

package-lock.json, package.json, src/ambient.d.ts
Removes `node-abi` from `ambient.d.ts` and uses the DefinitelyTyped package.
=> chore: use @types/node-abi

src/module-rebuilder.ts, test/rebuild.ts
I am building my electron project with electron-forge and I have some native dependencies. I noticed that Electron Forge is creating a `11.2.0` folder in my project which I traced down to node-gyp not getting the correct devDir.
The root cause seems to be that the `--devdir` option is parsed inside `bin/node-gyp.js` but electron-rebuild is importing `lib/node-gyp.js` directly. This will fix it by setting the `NodeGyp.devDir` property directly.
=> fix: correctly set the devDir path for node-gyp

package.json, src/ambient.d.ts, yarn.lock
Use `@types/detect-libc` instead of the ambient type declaration.
=> build: use detect-libc types

package.json, yarn.lock
This PR bumps node-abi to ^3.0.0, to accomodate a recent major bump that disables versions of Node older than Node 10.
=> chore: bump node-abi to ^3.0.0

src/cache.ts, src/cli.ts, src/module-rebuilder.ts, src/module-type/index.ts, src/module-walker.ts, src/rebuild.ts, src/types.ts
This is pretty much a lift-and-shift to reduce the amount of logic in `src/rebuild.ts` that's not directly related to rebuilding multiple native modules. The module walker extraction is particularly useful for the upcoming replacement of that logic (see #356).
There's also a small refactor to avoid a circular import between `src/rebuild.ts` and `src/module-rebuilder.ts`.
=> refactor: extract module walker & cache key logic to separate files

package.json, src/module-type/node-gyp.ts, test/helpers/module-setup.ts, test/module-type-node-gyp.ts, yarn.lock
Since node-gyp >= 8.4.0, building modules for old versions of Electron requires passing `--force-process-config` due to them lacking a valid config.gypi in their headers.
See also https://github.com/nodejs/node-gyp/pull/2497.
=> fix: require node-gyp@^8.4.0 & handle old Electron versions

package.json, yarn.lock
=> fix(deps): upgrade lzma-native to ^8.0.5 for prebuilt macOS/arm64 binaries

src/module-type/node-gyp.ts
As in title, `>=` semver satisfies checks are flawed and don't consider anything that is a prerelease to satisfy.  So let's just compare the major which is all we actually care about anyway
=> fix: ensure force-process-config is not passed to prerelease v20+

src/clang-fetcher.ts, src/module-type/node-gyp.ts
Addresses e/e issue [34209](https://github.com/electron/electron/issues/34209) while 20.0.0-beta.1 is in beta.
This PR adds a compile flag for `-std=c++17` when using Electron 20 or higher.
=> fix: add std=c++17 flag for e20+

package.json, src/clang-fetcher.ts, src/module-rebuilder.ts, src/module-type/node-gyp/node-gyp.ts, src/module-type/node-gyp/worker.ts, src/module-type/prebuild-install.ts, src/rebuild.ts, test/arch.ts, test/electron-locator.ts, test/fixture/native-app1/package.json, test/helpers/module-setup.ts, test/module-type-node-gyp.ts, test/module-type-prebuild-install.ts, test/module-type-prebuildify.ts, test/read-package-json.ts, test/rebuild-yarnworkspace.ts, test/rebuild.ts, test/search-module.ts, tsconfig.json
This refactors the node-gyp logic to run inside a forked child worker so that we can effectively run multiple at the same time without issues.
This also cleans up some stuff around how we build / test to make this easier too.
This PR doesn't change the default but it makes our tests ~33% faster when running locally with `parallel` mode instead of `sequential`
Example of this change + parallel vs current `main`
| Before | After |
| -------|-------|
| <img width="286" alt="image" src="https://user-images.githubusercontent.com/6634592/231422930-05ba5416-53e4-4c00-9dc7-3b9515d653ec.png"> | <img width="281" alt="image" src="https://user-images.githubusercontent.com/6634592/231423060-2821c094-37a3-4006-8928-7b8cb07aaeee.png"> |
You'll only get this perf boost if you manually enable parallel …
=> perf: use worker processes for node-gyp rebuilds

src/module-type/node-gyp.ts, test/fixture/napi-build-version/package.json, test/fixture/native-app1/package.json, test/helpers/module-setup.ts, test/module-type-node-gyp.ts, test/module-type-prebuild-install.ts, test/rebuild-napibuildversion.ts, test/rebuild-yarnworkspace.ts, test/rebuild.ts
fix: replacing macro `{napi_build_version}` in binary filename by using `binary.napi_build_versions` in package.json. Fixes: #554
Added unit test for offending module: `"sqlite3": "5.1.6"`
Tested on mac for arm64 and x64 rebuilds
Related:
https://github.com/electron-userland/electron-builder/issues/7473
Original PR credit to https://github.com/electron/rebuild/pull/1076 (I just added tests as requested)
=> fix: replacing macro {napi_build_version} in binary filename

.circleci/config.yml
=> ci: Remove legacy Python 2 from CircleCI

.circleci/config.yml, test/rebuild-napibuildversion.ts
Supersedes #1060
Supersedes #1085 (this PR tests a larger matrix of versions, including on macOS and Windows)
This was a real headache of conflicting bugs but managed to get a config that goes green for the full matrix:
* Tests against Node.js 20.2.0 because 20.3.0 has a bug (see comment in #1085) - also works around a panic in `nvm-windows` when installing 20.3.0
* Uses the `win/server-2022` executor because `win/vs2019` is no longer updated and has an old `nvm-windows` version which has a bug with npm versions
* [Enables long paths on Windows](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later) because with the `win/server-2022` executor the path of files being compiled ended up being …
=> ci: update test workflow and expand test matrix

package.json
Refs https://github.com/electron/electron/pull/38287.
Works around a `node-gyp` bug (fixed upstream) which is causing flakes for Windows jobs in CI.
=> test: prewarm Node headers cache

package.json, src/cli.ts, src/module-rebuilder.ts, src/module-type/node-pre-gyp.ts, src/rebuild.ts, src/types.ts, test/fixture/native-app1/package.json, test/helpers/module-setup.ts, test/module-type-node-pre-gyp.ts, test/module-type-prebuild-install.ts, test/rebuild-napibuildversion.ts, test/rebuild.ts, yarn.lock
[@mapbox/node-pre-gyp](https://www.npmjs.com/package/@mapbox/node-pre-gyp) is a popular choice for serving prebuilt native node module binaries. These changes add support for downloading prebuilt binaries using it as well as rebuilding in the case that no prebuilt binaries are found.
A `skipPrebuilds` option was added to give tests the ability to force rebuilds without using any prebuilt binary modules.
[node-sqlite3](https://github.com/TryGhost/node-sqlite3) is used to test for node-pre-gyp support.
resolves #367
=> feat: add node-pre-gyp support

src/rebuild.ts, test/rebuild.ts
There have been a few PRs for this over the years, this one will land 👍
=> feat: add ignoreModules to skip certain modules forcefully

package.json, src/module-type/node-pre-gyp.ts, test/module-type-node-pre-gyp.ts, yarn.lock
The arguments provided to node-pre-gyp are incomplete, resulting in prebuilt binaries not downloading the correct architecture. [From the readme](https://github.com/mapbox/node-pre-gyp#options), `--target_arch` and `--target_platform` are both used for downloading the prebuilt binaries. The `--arch` option seems to only be used when falling back to the `node-gyp` local build.
Also, if the binary already exists, `--update-binary` is required to redownload in the case of changing the targeted architecture. 
Follow up to https://github.com/electron/rebuild/pull/1095
=> fix: use 'target_arch' for node-pre-gyp

contributing.md
Follow-up to #1119, didn't notice this file linked directly to the removed file. Updates it to match the blurb in other `CONTRIBUTING.md` files in the org.
=> docs: fix CoC link in contributing.md

package.json, yarn.lock
I [recently updated](https://github.com/timfish/node-api-version/commit/6333f20b31f0ff4c1651f3c94da45fbed0ab33cd#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346) `node-api-version` to add support for API level 9. 
I should have just published this change as a patch release!
=> feat: Upgrade `node-api-version` to add support for NodeAPI level 9

package.json, src/arch.ts, src/clang-fetcher.ts, src/electron-locator.ts, src/module-type/index.ts, src/module-type/node-gyp/node-gyp.ts, src/module-type/node-gyp/worker.ts, src/module-type/prebuild-install.ts, src/module-type/prebuildify.ts, src/node-api.ts, src/search-module.ts, src/sysroot-fetcher.ts, test/electron-locator.ts, test/helpers/rebuild.ts, test/module-type-node-pre-gyp.ts, test/module-type-prebuild-install.ts, test/rebuild-napibuildversion.ts, test/rebuild-yarnworkspace.ts
Adding eslint rule to enforce semicolons and fixing related lines/errors
Created this PR due to this comment: https://github.com/electron/rebuild/pull/1153#discussion_r1775646121
Note: `"semi": "off"` is needed as `"@typescript-eslint/semi": "error",` supersedes `semi` and having both as `error` results in duplicated errors for each lint line. Ref: https://stackoverflow.com/a/72341604/3498974
=> chore: enforce semicolons via eslint

src/cache.ts, src/module-rebuilder.ts, src/module-type/node-gyp/node-gyp.ts, src/rebuild.ts, src/types.ts, test/module-type-node-gyp.ts, test/module-type-node-pre-gyp.ts, test/module-type-prebuild-install.ts, test/module-type-prebuildify.ts
Allow prebuilt binaries to be downloaded for target platform instead of hardcoded `process.platform`. Throws an error when attempting to cross-compile (`buildFromSource` || no prebuilds found)
Example: https://github.com/electron/rebuild/blob/cb372cdf09d9ca3ac8f1231608e4ebedddabe51c/src/module-type/node-pre-gyp.ts#L31
Origin of issue: https://github.com/electron/rebuild/blob/cb372cdf09d9ca3ac8f1231608e4ebedddabe51c/src/rebuild.ts#L135
Updated interface with new `platform` option and added docs
=> fix: cross-platform prebuild downloads

src/module-type/index.ts, src/module-type/node-pre-gyp.ts, src/module-type/prebuild-install.ts, src/module-type/prebuildify.ts, test/fixture/forked-module-test/package.json, test/fixture/native-app1/package.json, test/helpers/module-setup.ts, test/module-type-node-pre-gyp.ts, test/module-type-prebuild-install.ts, test/module-type-prebuildify.ts
It may sometimes be necessary to fork a prebuilt module package to fix an issue. In such cases, the rebuilder can miss prebuilt modules, forcing them to be built from source.
To avoid this, the module rebuilders will now also search for possible forked packages.
- `@mapbox/node-pre-gyp` may instead be `node-pre-gyp` or `@namespace/node-pre-gyp`
- `prebuild-install` may instead be `@namespace/prebuild-install`
- `prebuilds` may instead be `@namespace/prebuilds`
=> fix: allow using forks for prebuilt modules

package.json, src/module-type/node-gyp/worker.ts, test/fixture/native-app1/package.json, test/fixture/native-app1/yarn.lock, test/rebuild.ts, typings/ambient.d.ts, yarn.lock
This PR switches `@electron/rebuild` to a fork of the original and excellent `node-gyp` with only one feature added: Support for Node v12. We're doing so to fix `ModuleNotFoundError: No module named 'distutils'` errors on macOS Sequoia, which ships with Python 3.12 by default. Here is what happened:
- Python 3.12 has removed `distutils`, which `node-gyp` below v10 depended on.
- macOS Sequoia updated their default version of Python to 3.12.
- When installing a native Node addon, a lot of code bases suddenly showed `ModuleNotFoundError: No module named 'distutils'` error messages that are cryptic for anyone who doesn't have a full understanding of the dependency chain involved
This left us with the following choices:
1. **Tell the community to manually install either Python 3.11 or …
=> feat: Change node-gyp to @electron/node-gyp

.github/workflows/release.yml
Follow-up to #1164, a copy and paste error led to using an outdated version here which doesn't work.
=> ci: bump continuousauth/action version

.github/workflows/test.yml, package.json, test/helpers/module-setup.ts, yarn.lock
This clears the audit. The new version of `mocha` requires Node.js >= 14 so this also drops Node.js 12 from our CI matrix - we'll be doing the Node.js minimum bump soon enough.
=> build(dev-deps): bump mocha to clear the audit

package.json, src/module-type/node-gyp/worker.ts, typings/ambient.d.ts, yarn.lock
Follow up to #1157 and #1167
Electron's ecosystem (and specifically `@electron/rebuild`) now requires Node 22 or higher and node-gyp has bumped their own dependency chain to include Python 3.12, fixing the original MacOS Sequoia compatibility issue ([see v10.2.0](https://github.com/nodejs/node-gyp/releases/tag/v10.2.0)).
This PR brings us back onto the original node-gyp package from our fork.
=> fix: return to node-gyp

.github/workflows/test.yml
We no longer support Node.js 14 and don't test on it so this exclude is a no-op.
=> ci: remove unused matrix exclude

src/fetcher.ts
Just swapping this in favor of the Node.js builtin.
=> refactor: use timers/promises

.github/workflows/test.yml
This is needed to pick up a fix so that the action works with org-wide SHA pinning enforced for GHA.
=> ci: bump codecov/codecov-action to 5.5.0
